permalink: /:year/:month/:day/:title.html
markdown: redcarpet
redcarpet:
   extensions: ["hard_wrap","autolink","tables","fenced_code_blocks","disable_indented_code_blocks","no_intra_emphasis","space_after_headers","underline"]

# 作者信息
author: 
  name: linkpwd
  email: l8nkp2d@gmail.com
  link: http://linkpwd.github.io
  github: http://github.com/linkpwd

# 站点信息
title: Linux运维开发记录－－linkpwd的个人笔记
description: 记录个人的学习生活笔记，记录个人的学习足迹：包括但不限于读书笔记，Linux运维自动化，监控，shell|python脚本，安全效率工具．　
url: http://linkpwd.github.io

# gavatar头像及Favicon
avatar: /public/upload/avatar/avatar.png
favicon: /public/upload/avatar/favicon.ico

